# networks:
#   fractal-e2e-network:
#     external: true

# Use a common block for all Airflow services
x-airflow-common: &airflow-common
  image: my-airflow-local:latest
  build:
    context: ./
  environment:
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_WEBSERVER_SECRET_KEY}
    - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
  volumes:
    - ${DAGS_FOLDER}:/opt/airflow/dags
    # - ./data_processing:/opt/airflow/plugins/data_processing
  user: "${AIRFLOW_UID:-50000}:0" # Best practice to avoid permission issues
  profiles: ["airflow"]

services:
  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin"
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    restart: always
    # networks:
    #     - fractal-e2e-network
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    restart: always
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

